-- INSERT furnitures INTO items TABLE
INSERT items (id, name_en, name_kr) VALUES(383, "acoustic guitar", "어쿠스틱기타");
INSERT items (id, name_en, name_kr) VALUES(3821, "air circulator", "서큘레이터");
INSERT items (id, name_en, name_kr) VALUES(846, "alto saxophone", "알토 색소폰");
INSERT items (id, name_en, name_kr) VALUES(1317, "anatomical model", "인체 모형");
INSERT items (id, name_en, name_kr) VALUES(7238, "anchor statue", "닻 장식");
INSERT items (id, name_en, name_kr) VALUES(7867, "angled signpost", "기울어진 이정표");
INSERT items (id, name_en, name_kr) VALUES(3957, "antique bed", "앤티크 침대");
INSERT items (id, name_en, name_kr) VALUES(3956, "antique bureau", "앤티크 뷰로");
INSERT items (id, name_en, name_kr) VALUES(3950, "antique chair", "앤티크 의자");
INSERT items (id, name_en, name_kr) VALUES(3954, "antique clock", "앤티크 시계");
INSERT items (id, name_en, name_kr) VALUES(3951, "antique console table", "앤티크 콘솔 테이블");
INSERT items (id, name_en, name_kr) VALUES(3958, "antique mini table", "앤티크 미니 테이블");
INSERT items (id, name_en, name_kr) VALUES(3952, "antique table", "앤티크 테이블");
INSERT items (id, name_en, name_kr) VALUES(3955, "antique vanity", "앤티크 화장대");
INSERT items (id, name_en, name_kr) VALUES(3959, "antique wardrobe", "앤티크 옷장");
INSERT items (id, name_en, name_kr) VALUES(4134, "apple chair", "사과 체어");
INSERT items (id, name_en, name_kr) VALUES(5956, "Aquarius urn", "물병자리 항아리");
INSERT items (id, name_en, name_kr) VALUES(8226, "arcade combat game", "슈팅 아케이드 게임");
INSERT items (id, name_en, name_kr) VALUES(8225, "arcade fighting game", "격투 아케이드 게임");
INSERT items (id, name_en, name_kr) VALUES(8227, "arcade mahjong game", "테이블 아케이드 게임");
INSERT items (id, name_en, name_kr) VALUES(12207, "arcade seat", "오락실 의자");
INSERT items (id, name_en, name_kr) VALUES(5954, "Aries rocking chair", "양자리 목마");
INSERT items (id, name_en, name_kr) VALUES(7839, "artisanal bug cage", "원목 채집통");
INSERT items (id, name_en, name_kr) VALUES(1439, "asteroid", "운석");
INSERT items (id, name_en, name_kr) VALUES(1445, "astronaut suit", "우주 비행사");
INSERT items (id, name_en, name_kr) VALUES(2740, "automatic washer", "세탁기");
INSERT items (id, name_en, name_kr) VALUES(3305, "baby chair", "유아용 의자");
INSERT items (id, name_en, name_kr) VALUES(3658, "bamboo basket", "대나무 바구니");
INSERT items (id, name_en, name_kr) VALUES(710, "bamboo bench", "대나무 벤치");
INSERT items (id, name_en, name_kr) VALUES(3555, "bamboo doll", "대나무 깜짝 상자");
INSERT items (id, name_en, name_kr) VALUES(3557, "bamboo floor lamp", "대나무 플로어 스탠드");
INSERT items (id, name_en, name_kr) VALUES(5979, "bamboo noodle slide", "흐르는 국수 장치");
INSERT items (id, name_en, name_kr) VALUES(3553, "bamboo partition", "대나무 파티션");
INSERT items (id, name_en, name_kr) VALUES(3551, "bamboo shelf", "대나무 쉘프");
INSERT items (id, name_en, name_kr) VALUES(10743, "bamboo speaker", "대나무 스피커");
INSERT items (id, name_en, name_kr) VALUES(10742, "bamboo stool", "대나무 스툴");
INSERT items (id, name_en, name_kr) VALUES(3556, "bamboo stopblock", "대나무 주차 멈춤 턱");
INSERT items (id, name_en, name_kr) VALUES(330, "barbecue", "바비큐 그릴");
INSERT items (id, name_en, name_kr) VALUES(4078, "barbell", "바벨");
INSERT items (id, name_en, name_kr) VALUES(1266, "barrel", "나무통");
INSERT items (id, name_en, name_kr) VALUES(1330, "basic teacher's desk", "교탁");
INSERT items (id, name_en, name_kr) VALUES(4226, "basketball hoop", "농구 골대");
INSERT items (id, name_en, name_kr) VALUES(1229, "bathroom sink", "세면대");
INSERT items (id, name_en, name_kr) VALUES(664, "beach chair", "선베드");
INSERT items (id, name_en, name_kr) VALUES(3468, "beach towel", "비치 타월");
INSERT items (id, name_en, name_kr) VALUES(3406, "beekeeper's hive", "벌통");
INSERT items (id, name_en, name_kr) VALUES(4098, "bidet", "수동 비데");
INSERT items (id, name_en, name_kr) VALUES(3966, "big festive tree", "큰 크리스마스트리");
INSERT items (id, name_en, name_kr) VALUES(863, "billiard table", "당구대");
INSERT items (id, name_en, name_kr) VALUES(331, "birdbath", "수반");
INSERT items (id, name_en, name_kr) VALUES(865, "birdcage", "새장");
INSERT items (id, name_en, name_kr) VALUES(333, "birdhouse", "새집");
INSERT items (id, name_en, name_kr) VALUES(3594, "birthday sign", "생일 보드");
INSERT items (id, name_en, name_kr) VALUES(3593, "birthday table", "생일 테이블");
INSERT items (id, name_en, name_kr) VALUES(6831, "blossom-viewing lantern", "벚꽃 초롱");
INSERT items (id, name_en, name_kr) VALUES(7150, "blue corner", "파란색 링 모서리");
INSERT items (id, name_en, name_kr) VALUES(1430, "bonfire", "캠프파이어");
INSERT items (id, name_en, name_kr) VALUES(3580, "bonsai shelf", "분재 진열대");
INSERT items (id, name_en, name_kr) VALUES(1853, "box corner sofa", "사각 소파 코너");
INSERT items (id, name_en, name_kr) VALUES(1852, "box sofa", "사각 소파");
INSERT items (id, name_en, name_kr) VALUES(12370, "Brake Tapper", "OK 게임 머신");
INSERT items (id, name_en, name_kr) VALUES(1157, "brick oven", "벽돌 가마");
INSERT items (id, name_en, name_kr) VALUES(3776, "brick well", "벽돌 우물");
INSERT items (id, name_en, name_kr) VALUES(8298, "bunk bed", "2층 침대");
INSERT items (id, name_en, name_kr) VALUES(12398, "Bunny Day arch", "이스터 아치");
INSERT items (id, name_en, name_kr) VALUES(12414, "Bunny Day bed", "이스터 침대");
INSERT items (id, name_en, name_kr) VALUES(12421, "Bunny Day festive balloons", "이스터 풍선 B");
INSERT items (id, name_en, name_kr) VALUES(12419, "Bunny Day merry balloons", "이스터 풍선 A");
INSERT items (id, name_en, name_kr) VALUES(12415, "Bunny Day stool", "이스터 스툴");
INSERT items (id, name_en, name_kr) VALUES(12436, "Bunny Day table", "이스터 테이블");
INSERT items (id, name_en, name_kr) VALUES(12420, "Bunny Day vanity", "이스터 화장대");
INSERT items (id, name_en, name_kr) VALUES(12437, "Bunny Day wardrobe", "이스터 옷장");
INSERT items (id, name_en, name_kr) VALUES(7805, "butter churn", "버터 교반기");
INSERT items (id, name_en, name_kr) VALUES(1277, "cacao tree", "카카오");
INSERT items (id, name_en, name_kr) VALUES(1429, "campfire", "모닥불");
INSERT items (id, name_en, name_kr) VALUES(1433, "campfire cookware", "반합");
INSERT items (id, name_en, name_kr) VALUES(4081, "camping cot", "캠핑용 침대");
INSERT items (id, name_en, name_kr) VALUES(12374, "campsite sign", "캠핑장 간판");
INSERT items (id, name_en, name_kr) VALUES(5959, "Cancer table", "게자리 테이블");
INSERT items (id, name_en, name_kr) VALUES(7392, "candy machine", "캔디 머신");
INSERT items (id, name_en, name_kr) VALUES(5957, "Capricorn ornament", "염소자리 모형");
INSERT items (id, name_en, name_kr) VALUES(7161, "cardboard bed", "박스 침대");
INSERT items (id, name_en, name_kr) VALUES(7163, "cardboard chair", "박스 의자");
INSERT items (id, name_en, name_kr) VALUES(7159, "cardboard sofa", "박스 소파");
INSERT items (id, name_en, name_kr) VALUES(7160, "cardboard table", "박스 테이블");
INSERT items (id, name_en, name_kr) VALUES(896, "cat tower", "캣타워");
INSERT items (id, name_en, name_kr) VALUES(1449, "cello", "첼로");
INSERT items (id, name_en, name_kr) VALUES(2012, "chalkboard", "칠판");
INSERT items (id, name_en, name_kr) VALUES(7264, "champion's pennant", "우승기");
INSERT items (id, name_en, name_kr) VALUES(1816, "changing room", "피팅 룸");
INSERT items (id, name_en, name_kr) VALUES(6031, "cherry-blossom branches", "벚나무 가지");
INSERT items (id, name_en, name_kr) VALUES(7409, "cherry-blossom pond stone", "벚꽃 돌 물받이");
INSERT items (id, name_en, name_kr) VALUES(6032, "cherry-blossom-petal pile", "벚나무 꽃잎 더미");
INSERT items (id, name_en, name_kr) VALUES(80, "clackercart", "장난감차");
INSERT items (id, name_en, name_kr) VALUES(1757, "claw-foot tub", "럭셔리 욕조");
INSERT items (id, name_en, name_kr) VALUES(717, "clay furnace", "아궁이 부엌");
INSERT items (id, name_en, name_kr) VALUES(4006, "climbing wall", "클라이밍 월");
INSERT items (id, name_en, name_kr) VALUES(9502, "clothes closet", "패션 케이스");
INSERT items (id, name_en, name_kr) VALUES(3229, "clothesline", "빨랫줄");
INSERT items (id, name_en, name_kr) VALUES(1778, "clothesline pole", "빨래 건조봉");
INSERT items (id, name_en, name_kr) VALUES(1112, "colorful wheel", "룰렛");
INSERT items (id, name_en, name_kr) VALUES(146, "cone", "칼라콘");
INSERT items (id, name_en, name_kr) VALUES(9568, "construction sign", "공사 간판");
INSERT items (id, name_en, name_kr) VALUES(7230, "cosmos shower", "코스모스 샤워기");
INSERT items (id, name_en, name_kr) VALUES(4412, "cotton-candy stall", "솜사탕 노점");
INSERT items (id, name_en, name_kr) VALUES(6829, "crescent-moon chair", "초승달 체어");
INSERT items (id, name_en, name_kr) VALUES(5676, "crewed spaceship", "유인 우주선");
INSERT items (id, name_en, name_kr) VALUES(3624, "cute bed", "큐트 침대");
INSERT items (id, name_en, name_kr) VALUES(3999, "cute chair", "큐트 체어");
INSERT items (id, name_en, name_kr) VALUES(3995, "cute DIY table", "큐트 DIY 테이블");
INSERT items (id, name_en, name_kr) VALUES(4002, "cute floor lamp", "큐트 플로어 스탠드");
INSERT items (id, name_en, name_kr) VALUES(3998, "cute sofa", "큐트 소파");
INSERT items (id, name_en, name_kr) VALUES(4000, "cute tea table", "큐트 티 테이블");
INSERT items (id, name_en, name_kr) VALUES(4001, "cute vanity", "큐트 화장대");
INSERT items (id, name_en, name_kr) VALUES(3997, "cute wardrobe", "큐트 옷장");
INSERT items (id, name_en, name_kr) VALUES(7153, "cypress bathtub", "노송나무 욕조");
INSERT items (id, name_en, name_kr) VALUES(1829, "cypress plant", "율마");
INSERT items (id, name_en, name_kr) VALUES(937, "dartboard", "다트 보드");
INSERT items (id, name_en, name_kr) VALUES(677, "deer scare", "대나무 분수");
INSERT items (id, name_en, name_kr) VALUES(1227, "deluxe washer", "드럼 세탁기");
INSERT items (id, name_en, name_kr) VALUES(3784, "den chair", "서재 의자");
INSERT items (id, name_en, name_kr) VALUES(3783, "den desk", "서재 책상");
INSERT items (id, name_en, name_kr) VALUES(4309, "destinations signpost", "섬 이정표");
INSERT items (id, name_en, name_kr) VALUES(3307, "digital scale", "체중계");
INSERT items (id, name_en, name_kr) VALUES(4137, "diner chair", "다이너 의자");
INSERT items (id, name_en, name_kr) VALUES(4138, "diner counter chair", "다이너 카운터 체어");
INSERT items (id, name_en, name_kr) VALUES(4139, "diner counter table", "다이너 카운터 테이블");
INSERT items (id, name_en, name_kr) VALUES(4142, "diner dining table", "다이너 다이닝 테이블");
INSERT items (id, name_en, name_kr) VALUES(4441, "diner mini table", "다이너 미니 테이블");
INSERT items (id, name_en, name_kr) VALUES(4143, "diner neon sign", "다이너 네온 간판");
INSERT items (id, name_en, name_kr) VALUES(4141, "diner sofa", "다이너 소파");
INSERT items (id, name_en, name_kr) VALUES(2020, "director's chair", "영화감독 의자");
INSERT items (id, name_en, name_kr) VALUES(1241, "DIY workbench", "DIY 작업대");
INSERT items (id, name_en, name_kr) VALUES(941, "DJ's turntable", "DJ 테이블");
INSERT items (id, name_en, name_kr) VALUES(1799, "doghouse", "개집");
INSERT items (id, name_en, name_kr) VALUES(2554, "double sofa", "더블 소파");
INSERT items (id, name_en, name_kr) VALUES(4109, "double-door refrigerator", "양문형 냉장고");
INSERT items (id, name_en, name_kr) VALUES(1802, "drink machine", "음료수 자동판매기");
INSERT items (id, name_en, name_kr) VALUES(2319, "drinking fountain", "음수대");
INSERT items (id, name_en, name_kr) VALUES(1803, "drum set", "드럼");
INSERT items (id, name_en, name_kr) VALUES(7789, "drying rack", "빨래 건조대");
INSERT items (id, name_en, name_kr) VALUES(950, "effects rack", "이펙터 장비");
INSERT items (id, name_en, name_kr) VALUES(7865, "elaborate kimono stand", "호화로운 기모노 걸이");
INSERT items (id, name_en, name_kr) VALUES(1804, "electric bass", "일렉트릭 베이스 기타");
INSERT items (id, name_en, name_kr) VALUES(1645, "electric guitar", "일렉트릭기타 ES2");
INSERT items (id, name_en, name_kr) VALUES(7654, "electric kick scooter", "전동 킥보드");
INSERT items (id, name_en, name_kr) VALUES(86, "elephant slide", "코끼리 미끄럼틀");
INSERT items (id, name_en, name_kr) VALUES(1598, "exercise ball", "짐 볼");
INSERT items (id, name_en, name_kr) VALUES(287, "exercise bike", "자전거 머신");
INSERT items (id, name_en, name_kr) VALUES(3820, "fan", "선풍기");
INSERT items (id, name_en, name_kr) VALUES(1288, "fan palm", "아레카야자");
INSERT items (id, name_en, name_kr) VALUES(3991, "festive tree", "귀여운 크리스마스트리");
INSERT items (id, name_en, name_kr) VALUES(4100, "fire pit", "야외용 화덕");
INSERT items (id, name_en, name_kr) VALUES(742, "fireplace", "난로");
INSERT items (id, name_en, name_kr) VALUES(3581, "fish-drying rack", "생선 건조대");
INSERT items (id, name_en, name_kr) VALUES(3587, "fishing-rod stand", "낚싯대 스탠드");
INSERT items (id, name_en, name_kr) VALUES(1243, "flashy-flower sign", "화환");
INSERT items (id, name_en, name_kr) VALUES(12206, "flat garden rock", "낮은 바위");
INSERT items (id, name_en, name_kr) VALUES(2561, "floor lamp", "플로어 스탠드");
INSERT items (id, name_en, name_kr) VALUES(7135, "floor light", "바닥 조명");
INSERT items (id, name_en, name_kr) VALUES(3622, "floor seat", "좌식 의자");
INSERT items (id, name_en, name_kr) VALUES(7527, "flower stand", "플라워 스탠드");
INSERT items (id, name_en, name_kr) VALUES(1447, "flying saucer", "하늘 나는 원반");
INSERT items (id, name_en, name_kr) VALUES(7529, "folding chair", "강당 의자");
INSERT items (id, name_en, name_kr) VALUES(4014, "folding floor lamp", "관절형 플로어 스탠드");
INSERT items (id, name_en, name_kr) VALUES(1177, "foosball table", "테이블 축구");
INSERT items (id, name_en, name_kr) VALUES(12369, "fortune-cookie cart", "운세 쿠키 왜건");
INSERT items (id, name_en, name_kr) VALUES(8031, "fountain", "분수");
INSERT items (id, name_en, name_kr) VALUES(4135, "freezer", "냉동고");
INSERT items (id, name_en, name_kr) VALUES(7838, "fresh cooler", "멋진 아이스박스");
INSERT items (id, name_en, name_kr) VALUES(3499, "frozen arch", "얼음 아치");
INSERT items (id, name_en, name_kr) VALUES(3502, "frozen bed", "얼음 침대");
INSERT items (id, name_en, name_kr) VALUES(3503, "frozen chair", "얼음 의자");
INSERT items (id, name_en, name_kr) VALUES(3505, "frozen counter", "얼음 카운터");
INSERT items (id, name_en, name_kr) VALUES(3498, "frozen partition", "얼음 파티션");
INSERT items (id, name_en, name_kr) VALUES(3500, "frozen pillar", "얼음 기둥");
INSERT items (id, name_en, name_kr) VALUES(3501, "frozen sculpture", "얼음 조각상");
INSERT items (id, name_en, name_kr) VALUES(3497, "frozen table", "얼음 테이블");
INSERT items (id, name_en, name_kr) VALUES(3504, "frozen tree", "얼음 트리");
INSERT items (id, name_en, name_kr) VALUES(3230, "futon", "이불");
INSERT items (id, name_en, name_kr) VALUES(9767, "garbage bin", "이동식 쓰레기통");
INSERT items (id, name_en, name_kr) VALUES(2555, "garbage can", "양철 쓰레기통");
INSERT items (id, name_en, name_kr) VALUES(2556, "garbage pail", "뚜껑 쓰레기통");
INSERT items (id, name_en, name_kr) VALUES(3509, "garden bench", "가든 벤치");
INSERT items (id, name_en, name_kr) VALUES(1631, "garden faucet", "정원 수도꼭지");
INSERT items (id, name_en, name_kr) VALUES(1628, "garden lantern", "정원 랜턴");
INSERT items (id, name_en, name_kr) VALUES(729, "garden rock", "평범한 정원 돌");
INSERT items (id, name_en, name_kr) VALUES(8419, "garden wagon", "원예 왜건");
INSERT items (id, name_en, name_kr) VALUES(3251, "gas range", "오븐 가스레인지");
INSERT items (id, name_en, name_kr) VALUES(5960, "Gemini closet", "쌍둥이자리 옷장");
INSERT items (id, name_en, name_kr) VALUES(1504, "giant teddy bear", "특대 곰인형");
INSERT items (id, name_en, name_kr) VALUES(981, "go board", "바둑판");
INSERT items (id, name_en, name_kr) VALUES(8825, "golden casket", "황금 관");
INSERT items (id, name_en, name_kr) VALUES(3473, "golden seat", "황금 벤치");
INSERT items (id, name_en, name_kr) VALUES(3472, "golden toilet", "황금 변기");
INSERT items (id, name_en, name_kr) VALUES(1632, "golf bag", "골프백");
INSERT items (id, name_en, name_kr) VALUES(4075, "gong", "징");
INSERT items (id, name_en, name_kr) VALUES(7109, "grand Atlas moth model", "#N/A");
INSERT items (id, name_en, name_kr) VALUES(7090, "grand b. dragonfly model", "#N/A");
INSERT items (id, name_en, name_kr) VALUES(1875, "grand piano", "그랜드 피아노");
INSERT items (id, name_en, name_kr) VALUES(7051, "grand Q. A. birdwing model", "#N/A");
INSERT items (id, name_en, name_kr) VALUES(530, "grass standee", "연극용 잔디");
INSERT items (id, name_en, name_kr) VALUES(4269, "green-leaf pile", "초록 낙엽");
INSERT items (id, name_en, name_kr) VALUES(1620, "hammock", "해먹");
INSERT items (id, name_en, name_kr) VALUES(7229, "handcart", "외바퀴 손수레");
INSERT items (id, name_en, name_kr) VALUES(987, "harp", "하프");
INSERT items (id, name_en, name_kr) VALUES(3675, "hay bed", "건초 침대");
INSERT items (id, name_en, name_kr) VALUES(722, "hearth", "노");
INSERT items (id, name_en, name_kr) VALUES(531, "hedge standee", "연극용 산울타리");
INSERT items (id, name_en, name_kr) VALUES(790, "hi-fi stereo", "고급 오디오");
INSERT items (id, name_en, name_kr) VALUES(793, "high-end stereo", "멀티 오디오");
INSERT items (id, name_en, name_kr) VALUES(4113, "hose reel", "호스 릴");
INSERT items (id, name_en, name_kr) VALUES(4108, "illuminated present", "선물 일루미네이션");
INSERT items (id, name_en, name_kr) VALUES(4074, "illuminated reindeer", "순록 일루미네이션");
INSERT items (id, name_en, name_kr) VALUES(4131, "illuminated snowflakes", "눈꽃 일루미네이션");
INSERT items (id, name_en, name_kr) VALUES(4066, "illuminated tree", "트리 일루미네이션");
INSERT items (id, name_en, name_kr) VALUES(3973, "imperial bed", "오리엔탈 침대");
INSERT items (id, name_en, name_kr) VALUES(3972, "imperial chest", "오리엔탈 수납장");
INSERT items (id, name_en, name_kr) VALUES(7797, "imperial dining chair", "중국풍 의자");
INSERT items (id, name_en, name_kr) VALUES(7796, "imperial dining table", "중화요리 테이블");
INSERT items (id, name_en, name_kr) VALUES(3974, "imperial low table", "오리엔탈 낮은 테이블");
INSERT items (id, name_en, name_kr) VALUES(3971, "imperial partition", "오리엔탈 파티션");
INSERT items (id, name_en, name_kr) VALUES(3962, "inflatable sofa", "에어 소파");
INSERT items (id, name_en, name_kr) VALUES(9642, "iron closet", "아이언 옷장");
INSERT items (id, name_en, name_kr) VALUES(2553, "iron frame", "철골");
INSERT items (id, name_en, name_kr) VALUES(1625, "iron garden bench", "아이언 가든 벤치");
INSERT items (id, name_en, name_kr) VALUES(1626, "iron garden chair", "아이언 가든 체어");
INSERT items (id, name_en, name_kr) VALUES(1627, "iron garden table", "아이언 가든 테이블");
INSERT items (id, name_en, name_kr) VALUES(3561, "iron hanger stand", "아이언 스탠드 행거");
INSERT items (id, name_en, name_kr) VALUES(3563, "iron shelf", "아이언 쉘프");
INSERT items (id, name_en, name_kr) VALUES(3560, "iron worktable", "아이언 작업용 책상");
INSERT items (id, name_en, name_kr) VALUES(7531, "ironing board", "다리미판");
INSERT items (id, name_en, name_kr) VALUES(3200, "ironwood bed", "아이언우드 침대");
INSERT items (id, name_en, name_kr) VALUES(3195, "ironwood cart", "아이언우드 왜건");
INSERT items (id, name_en, name_kr) VALUES(3193, "ironwood chair", "아이언우드 체어");
INSERT items (id, name_en, name_kr) VALUES(3271, "ironwood cupboard", "아이언우드 찬장");
INSERT items (id, name_en, name_kr) VALUES(3943, "ironwood DIY workbench", "아이언우드 DIY 테이블");
INSERT items (id, name_en, name_kr) VALUES(3196, "ironwood dresser", "아이언우드 수납장");
INSERT items (id, name_en, name_kr) VALUES(3270, "ironwood kitchenette", "아이언우드 키친");
INSERT items (id, name_en, name_kr) VALUES(3194, "ironwood low table", "아이언우드 낮은 테이블");
INSERT items (id, name_en, name_kr) VALUES(3191, "ironwood table", "아이언우드 테이블");
INSERT items (id, name_en, name_kr) VALUES(5931, "jail bars", "감옥 문");
INSERT items (id, name_en, name_kr) VALUES(2596, "juicy-apple TV", "사과 TV");
INSERT items (id, name_en, name_kr) VALUES(791, "jukebox", "주크박스");
INSERT items (id, name_en, name_kr) VALUES(4008, "kettle bathtub", "가마솥 욕조");
INSERT items (id, name_en, name_kr) VALUES(7682, "kimono stand", "기모노 걸이");
INSERT items (id, name_en, name_kr) VALUES(998, "kitchen island", "아일랜드 키친");
INSERT items (id, name_en, name_kr) VALUES(7803, "kitty litter box", "고양이용 화장실");
INSERT items (id, name_en, name_kr) VALUES(1849, "kotatsu", "이불탁자");
INSERT items (id, name_en, name_kr) VALUES(3412, "large cardboard boxes", "이삿짐 박스 L");
INSERT items (id, name_en, name_kr) VALUES(1621, "lawn chair", "비닐 체어");
INSERT items (id, name_en, name_kr) VALUES(338, "lawn mower", "잔디 깎기");
INSERT items (id, name_en, name_kr) VALUES(7788, "leaf campfire", "낙엽 모닥불");
INSERT items (id, name_en, name_kr) VALUES(7390, "leaf stool", "낙엽 스툴");
INSERT items (id, name_en, name_kr) VALUES(2013, "lecture-hall bench", "강의실 의자");
INSERT items (id, name_en, name_kr) VALUES(2014, "lecture-hall desk", "강의실 책상");
INSERT items (id, name_en, name_kr) VALUES(3345, "lifeguard chair", "안전 감시대");
INSERT items (id, name_en, name_kr) VALUES(2335, "lighthouse", "등대");
INSERT items (id, name_en, name_kr) VALUES(7236, "lily record player", "백합 레코드플레이어");
INSERT items (id, name_en, name_kr) VALUES(3621, "loft bed with desk", "벙커 침대");
INSERT items (id, name_en, name_kr) VALUES(4041, "log bed", "통나무 침대");
INSERT items (id, name_en, name_kr) VALUES(4042, "log bench", "통나무 벤치");
INSERT items (id, name_en, name_kr) VALUES(4039, "log chair", "통나무 소파");
INSERT items (id, name_en, name_kr) VALUES(4036, "log decorative shelves", "통나무 쉘프");
INSERT items (id, name_en, name_kr) VALUES(4040, "log dining table", "통나무 다이닝 테이블");
INSERT items (id, name_en, name_kr) VALUES(4044, "log extra-long sofa", "통나무 긴 소파");
INSERT items (id, name_en, name_kr) VALUES(4035, "log garden lounge", "통나무 가든 침대");
INSERT items (id, name_en, name_kr) VALUES(4043, "log round table", "통나무 둥근 테이블");
INSERT items (id, name_en, name_kr) VALUES(5973, "log stakes", "통나무 말뚝");
INSERT items (id, name_en, name_kr) VALUES(4038, "log stool", "통나무 스툴");
INSERT items (id, name_en, name_kr) VALUES(4080, "long bathtub", "욕조");
INSERT items (id, name_en, name_kr) VALUES(7681, "loom", "베틀");
INSERT items (id, name_en, name_kr) VALUES(1029, "low screen", "낮은 파티션");
INSERT items (id, name_en, name_kr) VALUES(1440, "lunar lander", "달착륙선");
INSERT items (id, name_en, name_kr) VALUES(1442, "lunar rover", "월면이동차");
INSERT items (id, name_en, name_kr) VALUES(1500, "Mama bear", "중간 곰인형");
INSERT items (id, name_en, name_kr) VALUES(9699, "Mama panda", "중간 판다");
INSERT items (id, name_en, name_kr) VALUES(144, "manhole cover", "맨홀");
INSERT items (id, name_en, name_kr) VALUES(7408, "maple-leaf pond stone", "낙엽 돌 물받이");
INSERT items (id, name_en, name_kr) VALUES(4121, "marimba", "마림바");
INSERT items (id, name_en, name_kr) VALUES(12368, "Market Place decoration", "햇살 광장 장식");
INSERT items (id, name_en, name_kr) VALUES(3411, "medium cardboard boxes", "이삿짐 박스 M");
INSERT items (id, name_en, name_kr) VALUES(1866, "menu chalkboard", "메뉴 칠판");
INSERT items (id, name_en, name_kr) VALUES(9503, "mic stand", "스탠드 마이크");
INSERT items (id, name_en, name_kr) VALUES(3122, "mini DIY workbench", "작은 DIY 작업대");
INSERT items (id, name_en, name_kr) VALUES(9766, "mini fridge", "미니 냉장고");
INSERT items (id, name_en, name_kr) VALUES(698, "moai statue", "모아이");
INSERT items (id, name_en, name_kr) VALUES(832, "modern office chair", "사무용 의자");
INSERT items (id, name_en, name_kr) VALUES(4722, "monster statue", "괴수");
INSERT items (id, name_en, name_kr) VALUES(4129, "monstera", "몬스테라");
INSERT items (id, name_en, name_kr) VALUES(1054, "moon", "달");
INSERT items (id, name_en, name_kr) VALUES(12208, "mossy garden rock", "이끼 낀 바위");
INSERT items (id, name_en, name_kr) VALUES(2614, "mountain bike", "마운틴 바이크");
INSERT items (id, name_en, name_kr) VALUES(532, "mountain standee", "연극용 산");
INSERT items (id, name_en, name_kr) VALUES(335, "Mr. Flamingo", "수컷 플라밍고");
INSERT items (id, name_en, name_kr) VALUES(336, "Mrs. Flamingo", "암컷 플라밍고");
INSERT items (id, name_en, name_kr) VALUES(7232, "mum cushion", "국화 스툴");
INSERT items (id, name_en, name_kr) VALUES(805, "mush lamp", "버섯 램프");
INSERT items (id, name_en, name_kr) VALUES(3808, "mush log", "버섯 원목");
INSERT items (id, name_en, name_kr) VALUES(4708, "mush low stool", "버섯 스툴");
INSERT items (id, name_en, name_kr) VALUES(3805, "mush parasol", "버섯 파라솔");
INSERT items (id, name_en, name_kr) VALUES(3806, "mush partition", "버섯 파티션");
INSERT items (id, name_en, name_kr) VALUES(808, "mush table", "버섯 테이블");
INSERT items (id, name_en, name_kr) VALUES(1058, "music stand", "보면대");
INSERT items (id, name_en, name_kr) VALUES(2586, "natural garden chair", "내추럴 가든 체어");
INSERT items (id, name_en, name_kr) VALUES(3396, "natural garden table", "내추럴 가든 테이블");
INSERT items (id, name_en, name_kr) VALUES(12332, "natural square table", "내추럴 스퀘어 테이블");
INSERT items (id, name_en, name_kr) VALUES(7152, "neutral corner", "뉴트럴 링 모서리");
INSERT items (id, name_en, name_kr) VALUES(6984, "ocean sunfish model", "#N/A");
INSERT items (id, name_en, name_kr) VALUES(840, "office desk", "사무용 책상");
INSERT items (id, name_en, name_kr) VALUES(1567, "oil barrel", "드럼통");
INSERT items (id, name_en, name_kr) VALUES(3819, "oil-barrel bathtub", "드럼통 욕조");
INSERT items (id, name_en, name_kr) VALUES(12371, "OK Motors sign", "OK 모터즈 간판");
INSERT items (id, name_en, name_kr) VALUES(1127, "old sewing machine", "오래된 재봉틀");
INSERT items (id, name_en, name_kr) VALUES(3615, "open-frame kitchen", "프레임 키친");
INSERT items (id, name_en, name_kr) VALUES(3975, "orange end table", "오렌지 사이드 테이블");
INSERT items (id, name_en, name_kr) VALUES(1131, "outdoor air conditioner", "에어컨 실외기");
INSERT items (id, name_en, name_kr) VALUES(1111, "outdoor bath", "노천온천");
INSERT items (id, name_en, name_kr) VALUES(3947, "outdoor bench", "아웃도어 벤치");
INSERT items (id, name_en, name_kr) VALUES(7526, "outdoor generator", "아웃도어 캠핑용 발전기");
INSERT items (id, name_en, name_kr) VALUES(6033, "outdoor picnic set", "피크닉 세트");
INSERT items (id, name_en, name_kr) VALUES(3946, "outdoor table", "아웃도어 테이블");
INSERT items (id, name_en, name_kr) VALUES(688, "pagoda", "5층탑");
INSERT items (id, name_en, name_kr) VALUES(7259, "palm-tree lamp", "야자수 램프");
INSERT items (id, name_en, name_kr) VALUES(7237, "pansy table", "팬지 테이블");
INSERT items (id, name_en, name_kr) VALUES(4023, "pants press", "팬츠 프레스");
INSERT items (id, name_en, name_kr) VALUES(1499, "Papa bear", "큰 곰인형");
INSERT items (id, name_en, name_kr) VALUES(9700, "Papa panda", "큰 판다");
INSERT items (id, name_en, name_kr) VALUES(725, "paper lantern", "사방등");
INSERT items (id, name_en, name_kr) VALUES(2352, "parabolic antenna", "위성 안테나");
INSERT items (id, name_en, name_kr) VALUES(3595, "park clock", "공원 시계");
INSERT items (id, name_en, name_kr) VALUES(4127, "peach chair", "복숭아 체어");
INSERT items (id, name_en, name_kr) VALUES(4546, "pear bed", "배 침대");
INSERT items (id, name_en, name_kr) VALUES(1263, "pear wardrobe", "배 옷장");
INSERT items (id, name_en, name_kr) VALUES(7802, "pet bed", "반려동물 침대");
INSERT items (id, name_en, name_kr) VALUES(1185, "phone box", "공중전화 부스");
INSERT items (id, name_en, name_kr) VALUES(3681, "piano bench", "피아노 의자");
INSERT items (id, name_en, name_kr) VALUES(1023, "pile of leaves", "낙엽");
INSERT items (id, name_en, name_kr) VALUES(7048, "pile of zen cushions", "방석 더미");
INSERT items (id, name_en, name_kr) VALUES(1087, "pinball machine", "핀볼 게임기");
INSERT items (id, name_en, name_kr) VALUES(5963, "Pisces lamp", "물고기자리 램프");
INSERT items (id, name_en, name_kr) VALUES(3683, "plain sink", "소박한 세면대");
INSERT items (id, name_en, name_kr) VALUES(3692, "plain wooden shop sign", "소박한 목제 간판");
INSERT items (id, name_en, name_kr) VALUES(3348, "plastic pool", "비닐 풀");
INSERT items (id, name_en, name_kr) VALUES(3430, "playground gym", "정글짐");
INSERT items (id, name_en, name_kr) VALUES(1329, "podium", "교단");
INSERT items (id, name_en, name_kr) VALUES(7393, "pond stone", "돌 물받이");
INSERT items (id, name_en, name_kr) VALUES(3596, "pool", "풀");
INSERT items (id, name_en, name_kr) VALUES(4102, "poolside bed", "수영장 침대");
INSERT items (id, name_en, name_kr) VALUES(1092, "popcorn machine", "팝콘 머신");
INSERT items (id, name_en, name_kr) VALUES(1234, "portable toilet", "이동식 화장실");
INSERT items (id, name_en, name_kr) VALUES(3346, "public bench", "공공 벤치");
INSERT items (id, name_en, name_kr) VALUES(7845, "pull-up-bar stand", "철봉");
INSERT items (id, name_en, name_kr) VALUES(4013, "punching bag", "샌드백");
INSERT items (id, name_en, name_kr) VALUES(8608, "pyramid", "피라미드");
INSERT items (id, name_en, name_kr) VALUES(7452, "raccoon figurine", "너구리 모형");
INSERT items (id, name_en, name_kr) VALUES(4053, "rattan armchair", "라탄 소파");
INSERT items (id, name_en, name_kr) VALUES(4052, "rattan bed", "라탄 침대");
INSERT items (id, name_en, name_kr) VALUES(4046, "rattan end table", "라탄 사이드 테이블");
INSERT items (id, name_en, name_kr) VALUES(4054, "rattan low table", "라탄 낮은 테이블");
INSERT items (id, name_en, name_kr) VALUES(4047, "rattan stool", "라탄 스툴");
INSERT items (id, name_en, name_kr) VALUES(4051, "rattan vanity", "라탄 화장대");
INSERT items (id, name_en, name_kr) VALUES(4049, "rattan wardrobe", "라탄 옷장");
INSERT items (id, name_en, name_kr) VALUES(4045, "rattan waste bin", "라탄 쓰레기통");
INSERT items (id, name_en, name_kr) VALUES(7151, "red corner", "빨간색 링 모서리");
INSERT items (id, name_en, name_kr) VALUES(4271, "red-leaf pile", "빨간 낙엽");
INSERT items (id, name_en, name_kr) VALUES(2713, "refrigerator", "냉장고");
INSERT items (id, name_en, name_kr) VALUES(2736, "retro fan", "복고풍 선풍기");
INSERT items (id, name_en, name_kr) VALUES(4140, "retro gas pump", "복고풍 주유기");
INSERT items (id, name_en, name_kr) VALUES(796, "retro stereo", "복고풍 스테레오");
INSERT items (id, name_en, name_kr) VALUES(1509, "robot hero", "히어로 로봇");
INSERT items (id, name_en, name_kr) VALUES(1644, "rock guitar", "일렉트릭기타 ES1");
INSERT items (id, name_en, name_kr) VALUES(1441, "rocket", "로켓");
INSERT items (id, name_en, name_kr) VALUES(1851, "rocket lamp", "슬라임 램프");
INSERT items (id, name_en, name_kr) VALUES(1103, "rocking chair", "흔들의자");
INSERT items (id, name_en, name_kr) VALUES(83, "rocking horse", "목마");
INSERT items (id, name_en, name_kr) VALUES(7235, "rose bed", "장미 침대");
INSERT items (id, name_en, name_kr) VALUES(2771, "round space heater", "둥근 스토브");
INSERT items (id, name_en, name_kr) VALUES(839, "safe", "금고");
INSERT items (id, name_en, name_kr) VALUES(1117, "sand castle", "모래성");
INSERT items (id, name_en, name_kr) VALUES(1116, "sandbox", "모래사장");
INSERT items (id, name_en, name_kr) VALUES(1443, "satellite", "인공위성");
INSERT items (id, name_en, name_kr) VALUES(3689, "sauna heater", "사우나 히터");
INSERT items (id, name_en, name_kr) VALUES(1120, "scarecrow", "허수아비");
INSERT items (id, name_en, name_kr) VALUES(4034, "scattered papers", "널려 있는 종이");
INSERT items (id, name_en, name_kr) VALUES(1308, "school chair", "학교 의자");
INSERT items (id, name_en, name_kr) VALUES(1328, "school desk", "학교 책상");
INSERT items (id, name_en, name_kr) VALUES(716, "screen", "병풍");
INSERT items (id, name_en, name_kr) VALUES(1126, "server", "서버");
INSERT items (id, name_en, name_kr) VALUES(1606, "serving cart", "서빙 카트");
INSERT items (id, name_en, name_kr) VALUES(4572, "shaded floor lamp", "심플 플로어 스탠드");
INSERT items (id, name_en, name_kr) VALUES(3977, "shell arch", "조개 아치");
INSERT items (id, name_en, name_kr) VALUES(3983, "shell bed", "조개 침대");
INSERT items (id, name_en, name_kr) VALUES(3982, "shell fountain", "조개 분수");
INSERT items (id, name_en, name_kr) VALUES(3978, "shell partition", "조개 파티션");
INSERT items (id, name_en, name_kr) VALUES(3979, "shell stool", "조개 스툴");
INSERT items (id, name_en, name_kr) VALUES(3980, "shell table", "조개 테이블");
INSERT items (id, name_en, name_kr) VALUES(4015, "shower booth", "샤워 부스");
INSERT items (id, name_en, name_kr) VALUES(3588, "signpost", "이정표");
INSERT items (id, name_en, name_kr) VALUES(7247, "silo", "저장탑");
INSERT items (id, name_en, name_kr) VALUES(1045, "silver mic", "실버 마이크");
INSERT items (id, name_en, name_kr) VALUES(7142, "simple DIY workbench", "소박한 DIY 작업대");
INSERT items (id, name_en, name_kr) VALUES(5338, "simple panel", "심플 패널");
INSERT items (id, name_en, name_kr) VALUES(2754, "simple well", "심플한 우물");
INSERT items (id, name_en, name_kr) VALUES(1326, "skeleton", "해골 모형");
INSERT items (id, name_en, name_kr) VALUES(1434, "sleeping bag", "침낭");
INSERT items (id, name_en, name_kr) VALUES(7281, "sleigh", "썰매");
INSERT items (id, name_en, name_kr) VALUES(3410, "small cardboard boxes", "이삿짐 박스 S");
INSERT items (id, name_en, name_kr) VALUES(1143, "smoker", "훈제 통");
INSERT items (id, name_en, name_kr) VALUES(971, "snack machine", "과자 자동판매기");
INSERT items (id, name_en, name_kr) VALUES(1149, "soccer goal", "축구 골대");
INSERT items (id, name_en, name_kr) VALUES(3416, "soft-serve lamp", "소프트아이스크림 램프");
INSERT items (id, name_en, name_kr) VALUES(2333, "solar panel", "태양열 패널");
INSERT items (id, name_en, name_kr) VALUES(8150, "South Pole", "남극점");
INSERT items (id, name_en, name_kr) VALUES(1444, "space shuttle", "우주왕복선");
INSERT items (id, name_en, name_kr) VALUES(7653, "speed bag", "스피드백");
INSERT items (id, name_en, name_kr) VALUES(8702, "sphinx", "스핑크스");
INSERT items (id, name_en, name_kr) VALUES(1153, "spinning wheel", "물레");
INSERT items (id, name_en, name_kr) VALUES(4379, "springy ride-on", "스프링 놀이 기구");
INSERT items (id, name_en, name_kr) VALUES(2775, "squat toilet", "화변기");
INSERT items (id, name_en, name_kr) VALUES(546, "stadiometer", "신장 측정기");
INSERT items (id, name_en, name_kr) VALUES(3617, "stall", "노점");
INSERT items (id, name_en, name_kr) VALUES(3445, "standard umbrella stand", "우산꽂이");
INSERT items (id, name_en, name_kr) VALUES(1217, "standing toilet", "소변기");
INSERT items (id, name_en, name_kr) VALUES(693, "Statue of Liberty", "자유의 여신상");
INSERT items (id, name_en, name_kr) VALUES(11941, "stone arch", "석제 아치");
INSERT items (id, name_en, name_kr) VALUES(7795, "stone lion-dog", "돌로 만든 사자상");
INSERT items (id, name_en, name_kr) VALUES(3398, "stone stool", "돌 스툴");
INSERT items (id, name_en, name_kr) VALUES(3397, "stone table", "돌 테이블");
INSERT items (id, name_en, name_kr) VALUES(11943, "stone tablet", "비석");
INSERT items (id, name_en, name_kr) VALUES(7043, "Stonehenge", "스톤헨지");
INSERT items (id, name_en, name_kr) VALUES(4070, "street organ", "배럴 오르간");
INSERT items (id, name_en, name_kr) VALUES(11942, "street piano", "스트리트 피아노");
INSERT items (id, name_en, name_kr) VALUES(3816, "streetlamp", "가로등");
INSERT items (id, name_en, name_kr) VALUES(7189, "studio spotlight", "스포트라이트");
INSERT items (id, name_en, name_kr) VALUES(7868, "surfboard", "서핑 보드");
INSERT items (id, name_en, name_kr) VALUES(1170, "swinging bench", "벤치 그네");
INSERT items (id, name_en, name_kr) VALUES(1171, "synthesizer", "신시사이저");
INSERT items (id, name_en, name_kr) VALUES(3616, "system kitchen", "시스템 키친");
INSERT items (id, name_en, name_kr) VALUES(1779, "table with cloth", "사각 테이블");
INSERT items (id, name_en, name_kr) VALUES(730, "tall garden rock", "키가 큰 정원 돌");
INSERT items (id, name_en, name_kr) VALUES(676, "tall lantern", "석등");
INSERT items (id, name_en, name_kr) VALUES(2776, "tankless toilet", "일체형 변기");
INSERT items (id, name_en, name_kr) VALUES(7391, "tatami bed", "돗자리 침대");
INSERT items (id, name_en, name_kr) VALUES(5961, "Taurus bathtub", "황소자리 욕조");
INSERT items (id, name_en, name_kr) VALUES(739, "tea table", "낮은 밥상");
INSERT items (id, name_en, name_kr) VALUES(1507, "teacup ride", "빙글빙글 커피 잔");
INSERT items (id, name_en, name_kr) VALUES(1186, "telescope", "망원경");
INSERT items (id, name_en, name_kr) VALUES(1181, "tennis table", "탁구대");
INSERT items (id, name_en, name_kr) VALUES(3415, "termite mound", "개미집");
INSERT items (id, name_en, name_kr) VALUES(5337, "three-tiered snowperson", "3단 눈사람");
INSERT items (id, name_en, name_kr) VALUES(4763, "throwback dino screen", "TOY 파티션");
INSERT items (id, name_en, name_kr) VALUES(4760, "throwback hat table", "TOY 테이블");
INSERT items (id, name_en, name_kr) VALUES(4758, "throwback mitt chair", "TOY 체어");
INSERT items (id, name_en, name_kr) VALUES(4759, "throwback race-car bed", "TOY 침대");
INSERT items (id, name_en, name_kr) VALUES(4761, "throwback rocket", "TOY 옷장");
INSERT items (id, name_en, name_kr) VALUES(343, "tiki torch", "횃불");
INSERT items (id, name_en, name_kr) VALUES(5635, "tiny library", "작은 무인 도서관");
INSERT items (id, name_en, name_kr) VALUES(1189, "tire stack", "쌓인 타이어");
INSERT items (id, name_en, name_kr) VALUES(2329, "tire toy", "타이어 놀이 기구");
INSERT items (id, name_en, name_kr) VALUES(1929, "toilet", "양변기");
INSERT items (id, name_en, name_kr) VALUES(4072, "toilet-cleaning set", "화장실 청소 세트");
INSERT items (id, name_en, name_kr) VALUES(7528, "tool cart", "도구 카트");
INSERT items (id, name_en, name_kr) VALUES(7525, "tool shelf", "공구 선반");
INSERT items (id, name_en, name_kr) VALUES(3078, "tourist telescope", "관광 망원경");
INSERT items (id, name_en, name_kr) VALUES(700, "Tower of Pisa", "피사의 사탑");
INSERT items (id, name_en, name_kr) VALUES(85, "train set", "철도 모형");
INSERT items (id, name_en, name_kr) VALUES(290, "treadmill", "러닝 머신");
INSERT items (id, name_en, name_kr) VALUES(533, "tree standee", "연극용 나무");
INSERT items (id, name_en, name_kr) VALUES(6081, "tree's bounty arch", "나무 열매 아치");
INSERT items (id, name_en, name_kr) VALUES(6080, "tree's bounty big tree", "커다란 나무 열매 트리");
INSERT items (id, name_en, name_kr) VALUES(1199, "tricycle", "세발자전거");
INSERT items (id, name_en, name_kr) VALUES(7261, "trophy case", "트로피 케이스");
INSERT items (id, name_en, name_kr) VALUES(7231, "tulip surprise box", "튤립 깜짝 상자");
INSERT items (id, name_en, name_kr) VALUES(1412, "TV camera", "TV 카메라");
INSERT items (id, name_en, name_kr) VALUES(833, "upright locker", "캐비닛");
INSERT items (id, name_en, name_kr) VALUES(1081, "upright piano", "업라이트 피아노");
INSERT items (id, name_en, name_kr) VALUES(908, "upright vacuum", "스틱 청소기");
INSERT items (id, name_en, name_kr) VALUES(9619, "utility pole", "전신주");
INSERT items (id, name_en, name_kr) VALUES(4026, "utility sink", "청소용 개수대");
INSERT items (id, name_en, name_kr) VALUES(907, "vacuum cleaner", "청소기");
INSERT items (id, name_en, name_kr) VALUES(8465, "velvet stool", "피아노 둥근 의자");
INSERT items (id, name_en, name_kr) VALUES(1221, "video camera", "비디오카메라");
INSERT items (id, name_en, name_kr) VALUES(4445, "vintage TV tray", "빈티지 접이식 협탁");
INSERT items (id, name_en, name_kr) VALUES(5955, "Virgo harp", "처녀자리 하프");
INSERT items (id, name_en, name_kr) VALUES(1232, "water cooler", "정수기");
INSERT items (id, name_en, name_kr) VALUES(2326, "water pump", "수동 펌프");
INSERT items (id, name_en, name_kr) VALUES(665, "wave breaker", "방파제 블록");
INSERT items (id, name_en, name_kr) VALUES(12402, "wedding arch", "웨딩 아치");
INSERT items (id, name_en, name_kr) VALUES(12401, "wedding bench", "웨딩 벤치");
INSERT items (id, name_en, name_kr) VALUES(12405, "wedding chair", "웨딩 체어");
INSERT items (id, name_en, name_kr) VALUES(12411, "wedding flower stand", "웨딩 플라워 스탠드");
INSERT items (id, name_en, name_kr) VALUES(12404, "wedding head table", "웨딩 메인 테이블");
INSERT items (id, name_en, name_kr) VALUES(12409, "wedding pipe organ", "웨딩 파이프 오르간");
INSERT items (id, name_en, name_kr) VALUES(12406, "wedding table", "웨딩 테이블");
INSERT items (id, name_en, name_kr) VALUES(12410, "wedding welcome board", "웨딩 안내 간판");
INSERT items (id, name_en, name_kr) VALUES(1452, "weight bench", "벤치프레스");
INSERT items (id, name_en, name_kr) VALUES(3446, "western-style stone", "서양식 묘석");
INSERT items (id, name_en, name_kr) VALUES(3444, "wheelchair", "휠체어");
INSERT items (id, name_en, name_kr) VALUES(1840, "whirlpool bath", "자쿠지 욕조");
INSERT items (id, name_en, name_kr) VALUES(4116, "whiteboard", "화이트보드");
INSERT items (id, name_en, name_kr) VALUES(5972, "wild log bench", "와일드 통나무 벤치");
INSERT items (id, name_en, name_kr) VALUES(7379, "wind turbine", "풍력 발전기");
INSERT items (id, name_en, name_kr) VALUES(4117, "wood-burning stove", "장작 스토브");
INSERT items (id, name_en, name_kr) VALUES(4125, "wooden bookshelf", "목제 책장");
INSERT items (id, name_en, name_kr) VALUES(880, "wooden bucket", "나무 양동이");
INSERT items (id, name_en, name_kr) VALUES(1913, "wooden chair", "목제 체어");
INSERT items (id, name_en, name_kr) VALUES(2560, "wooden chest", "목제 수납장");
INSERT items (id, name_en, name_kr) VALUES(7132, "wooden double bed", "목제 더블 침대");
INSERT items (id, name_en, name_kr) VALUES(3438, "wooden end table", "목제 사이드 테이블");
INSERT items (id, name_en, name_kr) VALUES(7137, "wooden full-length mirror", "목제 전신 거울");
INSERT items (id, name_en, name_kr) VALUES(7134, "wooden low table", "목제 낮은 테이블");
INSERT items (id, name_en, name_kr) VALUES(7133, "wooden mini table", "목제 미니 테이블");
INSERT items (id, name_en, name_kr) VALUES(2605, "wooden simple bed", "목제 싱글 침대");
INSERT items (id, name_en, name_kr) VALUES(3449, "wooden stool", "목제 스툴");
INSERT items (id, name_en, name_kr) VALUES(3439, "wooden table", "목제 테이블");
INSERT items (id, name_en, name_kr) VALUES(3436, "wooden wardrobe", "목제 옷장");
INSERT items (id, name_en, name_kr) VALUES(3490, "wooden waste bin", "나무 쓰레기통");
INSERT items (id, name_en, name_kr) VALUES(1557, "wooden-block bed", "나무블록 침대");
INSERT items (id, name_en, name_kr) VALUES(1559, "wooden-block bench", "나무블록 벤치");
INSERT items (id, name_en, name_kr) VALUES(1558, "wooden-block bookshelf", "나무블록 북 쉘프");
INSERT items (id, name_en, name_kr) VALUES(2558, "wooden-block chair", "나무블록 체어");
INSERT items (id, name_en, name_kr) VALUES(1561, "wooden-block chest", "나무블록 수납장");
INSERT items (id, name_en, name_kr) VALUES(3205, "wooden-block stereo", "나무블록 오디오");
INSERT items (id, name_en, name_kr) VALUES(5543, "wooden-block stool", "나무블록 스툴");
INSERT items (id, name_en, name_kr) VALUES(1565, "wooden-block table", "나무블록 테이블");
INSERT items (id, name_en, name_kr) VALUES(3702, "writing chair", "공부 의자");
INSERT items (id, name_en, name_kr) VALUES(3701, "writing desk", "공부 책상");
INSERT items (id, name_en, name_kr) VALUES(4270, "yellow-leaf pile", "노란 낙엽");
INSERT items (id, name_en, name_kr) VALUES(4132, "yucca", "유카");
INSERT items (id, name_en, name_kr) VALUES(7047, "zen cushion", "방석");
INSERT items (id, name_en, name_kr) VALUES(7317, "zen-style stone", "일본식 묘석");

INSERT tagas (category, content) VALUES('type', '가구');
SET @furniture_tag_id = (SELECT id FROM tags WHERE content LIKE '가구');

INSERT  item_tags (tag_id, item_id) 
SELECT  @furniture_tag_id, items.id 
FROM    items;







-- Insert Miscellaneous INTO items table
INSERT items (id, name_en, name_kr) VALUES(3948, "accessories stand", "액세서리 스탠드");
INSERT items (id, name_en, name_kr) VALUES(12579, "ACNH Nintendo Switch", "동물의 숲 Nintendo Switch");
INSERT items (id, name_en, name_kr) VALUES(7080, "agrias butterfly model", "아그리아스나비 모형");
INSERT items (id, name_en, name_kr) VALUES(7453, "aluminum briefcase", "듀랄루민 케이스");
INSERT items (id, name_en, name_kr) VALUES(849, "amp", "앰프");
INSERT items (id, name_en, name_kr) VALUES(3993, "analog kitchen scale", "주방용 저울");
INSERT items (id, name_en, name_kr) VALUES(6999, "anchovy model", "멸치 모형");
INSERT items (id, name_en, name_kr) VALUES(6933, "angelfish model", "천사어 모형");
INSERT items (id, name_en, name_kr) VALUES(11866, "ant farm", "개미 키우기 세트");
INSERT items (id, name_en, name_kr) VALUES(7053, "ant model", "개미 모형");
INSERT items (id, name_en, name_kr) VALUES(3949, "anthurium plant", "안수리움");
INSERT items (id, name_en, name_kr) VALUES(7006, "arapaima model", "피라루쿠 모형");
INSERT items (id, name_en, name_kr) VALUES(1753, "aroma pot", "아로마 포트");
INSERT items (id, name_en, name_kr) VALUES(6935, "arowana model", "아로와나 모형");
INSERT items (id, name_en, name_kr) VALUES(1501, "Baby bear", "작은 곰인형");
INSERT items (id, name_en, name_kr) VALUES(9698, "Baby panda", "작은 판다");
INSERT items (id, name_en, name_kr) VALUES(7082, "bagworm model", "도롱이벌레 모형");
INSERT items (id, name_en, name_kr) VALUES(2010, "ball", "볼");
INSERT items (id, name_en, name_kr) VALUES(3554, "bamboo candleholder", "대나무 촛대");
INSERT items (id, name_en, name_kr) VALUES(4093, "bamboo drum", "대나무 드럼");
INSERT items (id, name_en, name_kr) VALUES(5978, "bamboo lunch box", "대나무 도시락");
INSERT items (id, name_en, name_kr) VALUES(5976, "bamboo sphere", "대나무 공");
INSERT items (id, name_en, name_kr) VALUES(5977, "bamboo-shoot lamp", "죽순 램프");
INSERT items (id, name_en, name_kr) VALUES(6959, "barred knifejaw model", "돌돔 모형");
INSERT items (id, name_en, name_kr) VALUES(6943, "barreleye model", "데메니기스 모형");
INSERT items (id, name_en, name_kr) VALUES(9584, "beach ball", "비치 볼");
INSERT items (id, name_en, name_kr) VALUES(7096, "bell cricket model", "방울벌레 모형");
INSERT items (id, name_en, name_kr) VALUES(6937, "betta model", "베타 모형");
INSERT items (id, name_en, name_kr) VALUES(864, "bingo wheel", "빙고 머신");
INSERT items (id, name_en, name_kr) VALUES(3592, "birthday cake", "생일 케이크");
INSERT items (id, name_en, name_kr) VALUES(3591, "birthday candles", "생일 양초");
INSERT items (id, name_en, name_kr) VALUES(6931, "bitterling model", "납줄개 모형");
INSERT items (id, name_en, name_kr) VALUES(6938, "black bass model", "큰입배스 모형");
INSERT items (id, name_en, name_kr) VALUES(6951, "blowfish model", "복어 모형");
INSERT items (id, name_en, name_kr) VALUES(6963, "blue marlin model", "청새치 모형");
INSERT items (id, name_en, name_kr) VALUES(7118, "blue weevil beetle model", "유포루스바구미 모형");
INSERT items (id, name_en, name_kr) VALUES(6939, "bluegill model", "블루길 모형");
INSERT items (id, name_en, name_kr) VALUES(7599, "board game", "보드게임");
INSERT items (id, name_en, name_kr) VALUES(3582, "book", "책");
INSERT items (id, name_en, name_kr) VALUES(870, "book stands", "북엔드");
INSERT items (id, name_en, name_kr) VALUES(683, "bottled ship", "보틀쉽");
INSERT items (id, name_en, name_kr) VALUES(11283, "brine-shrimp aquarium", "브라인슈림프 수조");
INSERT items (id, name_en, name_kr) VALUES(1205, "bronze bug trophy", "동 곤충 트로피");
INSERT items (id, name_en, name_kr) VALUES(1202, "bronze fish trophy", "동 물고기 트로피");
INSERT items (id, name_en, name_kr) VALUES(7098, "bronze HHA trophy", "집 모양 동 트로피");
INSERT items (id, name_en, name_kr) VALUES(7046, "brown cicada model", "유지매미 모형");
INSERT items (id, name_en, name_kr) VALUES(12438, "Bunny Day basket", "이스터 바구니");
INSERT items (id, name_en, name_kr) VALUES(12413, "Bunny Day lamp", "이스터 램프");
INSERT items (id, name_en, name_kr) VALUES(6941, "butterfly fish model", "나비고기 모형");
INSERT items (id, name_en, name_kr) VALUES(889, "camp stove", "코펠");
INSERT items (id, name_en, name_kr) VALUES(2562, "candle", "양초");
INSERT items (id, name_en, name_kr) VALUES(3672, "cardboard box", "종이 상자");
INSERT items (id, name_en, name_kr) VALUES(6980, "carp model", "잉어 모형");
INSERT items (id, name_en, name_kr) VALUES(4122, "cartoonist's set", "만화가 세트");
INSERT items (id, name_en, name_kr) VALUES(1708, "cassette player", "더블 데크");
INSERT items (id, name_en, name_kr) VALUES(7136, "cat grass", "캣그라스");
INSERT items (id, name_en, name_kr) VALUES(6987, "catfish model", "메기 모형");
INSERT items (id, name_en, name_kr) VALUES(4719, "celebratory candles", "연회장 양초");
INSERT items (id, name_en, name_kr) VALUES(7407, "centipede model", "지네 모형");
INSERT items (id, name_en, name_kr) VALUES(7003, "char model", "열목어 모형");
INSERT items (id, name_en, name_kr) VALUES(7027, "cherry salmon model", "산천어 모형");
INSERT items (id, name_en, name_kr) VALUES(4011, "cherry speakers", "체리 스피커");
INSERT items (id, name_en, name_kr) VALUES(6030, "cherry-blossom bonsai", "벚나무 분재");
INSERT items (id, name_en, name_kr) VALUES(2770, "chessboard", "체스");
INSERT items (id, name_en, name_kr) VALUES(7095, "cicada shell model", "매미 허물 모형");
INSERT items (id, name_en, name_kr) VALUES(7070, "citrus long-horned b. model", "알락하늘소 모형");
INSERT items (id, name_en, name_kr) VALUES(4073, "classic pitcher", "도기 물병");
INSERT items (id, name_en, name_kr) VALUES(6981, "clown fish model", "흰동가리 모형");
INSERT items (id, name_en, name_kr) VALUES(3684, "coconut juice", "코코넛 주스");
INSERT items (id, name_en, name_kr) VALUES(7016, "coelacanth model", "실러캔스 모형");
INSERT items (id, name_en, name_kr) VALUES(918, "coffee cup", "커피 잔");
INSERT items (id, name_en, name_kr) VALUES(920, "coffee grinder", "커피밀");
INSERT items (id, name_en, name_kr) VALUES(7111, "common bluebottle model", "청띠제비나비 모형");
INSERT items (id, name_en, name_kr) VALUES(7085, "common butterfly model", "배추흰나비 모형");
INSERT items (id, name_en, name_kr) VALUES(3064, "cooler box", "아이스박스");
INSERT items (id, name_en, name_kr) VALUES(4009, "cordless phone", "무선 전화기");
INSERT items (id, name_en, name_kr) VALUES(7029, "crawfish model", "가재 모형");
INSERT items (id, name_en, name_kr) VALUES(1161, "cream and sugar", "슈거&밀크");
INSERT items (id, name_en, name_kr) VALUES(7077, "cricket model", "귀뚜라미 모형");
INSERT items (id, name_en, name_kr) VALUES(6929, "crucian carp model", "붕어 모형");
INSERT items (id, name_en, name_kr) VALUES(1792, "cushion", "쿠션");
INSERT items (id, name_en, name_kr) VALUES(4003, "cute music player", "큐트 오디오 플레이어");
INSERT items (id, name_en, name_kr) VALUES(3618, "cutting board", "도마");
INSERT items (id, name_en, name_kr) VALUES(7064, "cyclommatus stag model", "엘라푸스가위사슴벌레 모형");
INSERT items (id, name_en, name_kr) VALUES(6965, "dab model", "가자미 모형");
INSERT items (id, name_en, name_kr) VALUES(7024, "dace model", "황어 모형");
INSERT items (id, name_en, name_kr) VALUES(12140, "DAL model plane", "DAL 비행기 모형");
INSERT items (id, name_en, name_kr) VALUES(12139, "DAL mug", "DAL 머그컵");
INSERT items (id, name_en, name_kr) VALUES(685, "Dala horse", "달라헤스트");
INSERT items (id, name_en, name_kr) VALUES(7121, "damselfly model", "실잠자리 모형");
INSERT items (id, name_en, name_kr) VALUES(7058, "darner dragonfly model", "왕잠자리 모형");
INSERT items (id, name_en, name_kr) VALUES(1797, "decoy duck", "유인용 오리");
INSERT items (id, name_en, name_kr) VALUES(1868, "desk mirror", "책상용 거울");
INSERT items (id, name_en, name_kr) VALUES(3590, "desktop computer", "데스크톱 PC");
INSERT items (id, name_en, name_kr) VALUES(2731, "digital alarm clock", "디지털 알람 시계");
INSERT items (id, name_en, name_kr) VALUES(1798, "dinnerware", "식기");
INSERT items (id, name_en, name_kr) VALUES(3400, "dish-drying rack", "식기 건조대");
INSERT items (id, name_en, name_kr) VALUES(7057, "diving beetle model", "물방개 모형");
INSERT items (id, name_en, name_kr) VALUES(1750, "document stack", "서류 더미");
INSERT items (id, name_en, name_kr) VALUES(1495, "dolly", "인형");
INSERT items (id, name_en, name_kr) VALUES(7837, "dorado model", "황금연어 모형");
INSERT items (id, name_en, name_kr) VALUES(7114, "drone beetle model", "풍이 모형");
INSERT items (id, name_en, name_kr) VALUES(7066, "dung beetle model", "쇠똥구리 모형");
INSERT items (id, name_en, name_kr) VALUES(7074, "earth-boring dung b. model", "보라금풍뎅이 모형");
INSERT items (id, name_en, name_kr) VALUES(4071, "electronics kit", "전자 공작 세트");
INSERT items (id, name_en, name_kr) VALUES(7086, "emperor butterfly model", "몰포나비 모형");
INSERT items (id, name_en, name_kr) VALUES(954, "espresso maker", "에스프레소 머신");
INSERT items (id, name_en, name_kr) VALUES(4110, "essay set", "작가 세트");
INSERT items (id, name_en, name_kr) VALUES(7063, "evening cicada model", "쓰르라미 모형");
INSERT items (id, name_en, name_kr) VALUES(2772, "fancy violin", "바이올린");
INSERT items (id, name_en, name_kr) VALUES(4101, "fax machine", "팩스");
INSERT items (id, name_en, name_kr) VALUES(12230, "festive top set", "축제 팽이");
INSERT items (id, name_en, name_kr) VALUES(3963, "film projector", "영사기");
INSERT items (id, name_en, name_kr) VALUES(7065, "firefly model", "반디 모형");
INSERT items (id, name_en, name_kr) VALUES(5970, "firewood", "장작");
INSERT items (id, name_en, name_kr) VALUES(5935, "flea model", "벼룩 모형");
INSERT items (id, name_en, name_kr) VALUES(4094, "floating-biotope planter", "비오톱");
INSERT items (id, name_en, name_kr) VALUES(7260, "floor sign", "플로어 사인");
INSERT items (id, name_en, name_kr) VALUES(7060, "fly model", "파리 모형");
INSERT items (id, name_en, name_kr) VALUES(4381, "football", "럭비공");
INSERT items (id, name_en, name_kr) VALUES(6940, "football fish model", "초롱아귀 모형");
INSERT items (id, name_en, name_kr) VALUES(3961, "fortune-telling set", "운세 세트");
INSERT items (id, name_en, name_kr) VALUES(8418, "fragrance diffuser", "아로마 디퓨저");
INSERT items (id, name_en, name_kr) VALUES(10244, "fragrance sticks", "아로마 스틱");
INSERT items (id, name_en, name_kr) VALUES(6946, "freshwater goby model", "동사리 모형");
INSERT items (id, name_en, name_kr) VALUES(6962, "frog model", "개구리 모형");
INSERT items (id, name_en, name_kr) VALUES(4279, "frozen-treat set", "막대 아이스크림");
INSERT items (id, name_en, name_kr) VALUES(975, "fruit basket", "과일 바구니");
INSERT items (id, name_en, name_kr) VALUES(4104, "frying pan", "프라이팬");
INSERT items (id, name_en, name_kr) VALUES(6952, "gar model", "가아 모형");
INSERT items (id, name_en, name_kr) VALUES(1624, "garden gnome", "노움 모형");
INSERT items (id, name_en, name_kr) VALUES(7078, "giant cicada model", "곰매미 모형");
INSERT items (id, name_en, name_kr) VALUES(7007, "giant snakehead model", "가물치 모형");
INSERT items (id, name_en, name_kr) VALUES(7092, "giant stag model", "왕사슴벌레 모형");
INSERT items (id, name_en, name_kr) VALUES(7010, "giant trevally model", "무명갈전갱이 모형");
INSERT items (id, name_en, name_kr) VALUES(7120, "giant water bug model", "물장군 모형");
INSERT items (id, name_en, name_kr) VALUES(4230, "glass holder with candle", "유리컵 양초");
INSERT items (id, name_en, name_kr) VALUES(1411, "globe", "지구의");
INSERT items (id, name_en, name_kr) VALUES(3065, "gold bars", "금괴");
INSERT items (id, name_en, name_kr) VALUES(1203, "gold bug trophy", "금 곤충 트로피");
INSERT items (id, name_en, name_kr) VALUES(1200, "gold fish trophy", "금 물고기 트로피");
INSERT items (id, name_en, name_kr) VALUES(7032, "gold HHA trophy", "집 모양 금 트로피");
INSERT items (id, name_en, name_kr) VALUES(11260, "golden arowana model", "금 아로와나");
INSERT items (id, name_en, name_kr) VALUES(3772, "golden candlestick", "황금 촛대");
INSERT items (id, name_en, name_kr) VALUES(3810, "golden dishes", "황금 식기");
INSERT items (id, name_en, name_kr) VALUES(5941, "golden dung beetle", "금 쇠똥구리");
INSERT items (id, name_en, name_kr) VALUES(7093, "golden stag model", "황금사슴벌레 모형");
INSERT items (id, name_en, name_kr) VALUES(6953, "golden trout model", "금송어 모형");
INSERT items (id, name_en, name_kr) VALUES(6930, "goldfish model", "금붕어 모형");
INSERT items (id, name_en, name_kr) VALUES(7115, "grand giraffe stag model", "위대한 사슴벌레 모형");
INSERT items (id, name_en, name_kr) VALUES(7059, "grand goliath beetle model", "위대한 꽃무지 모형");
INSERT items (id, name_en, name_kr) VALUES(5924, "grand h. hercules model", "위대한 장수풍뎅이 모형");
INSERT items (id, name_en, name_kr) VALUES(7073, "grasshopper model", "여치 모형");
INSERT items (id, name_en, name_kr) VALUES(7113, "great purple emperor model", "왕오색나비 모형");
INSERT items (id, name_en, name_kr) VALUES(7013, "great white shark model", "상어 모형");
INSERT items (id, name_en, name_kr) VALUES(6954, "guppy model", "구피 모형");
INSERT items (id, name_en, name_kr) VALUES(7015, "hammerhead shark model", "귀상어 모형");
INSERT items (id, name_en, name_kr) VALUES(1348, "hamster cage", "햄스터 철장");
INSERT items (id, name_en, name_kr) VALUES(3960, "handy water cooler", "워터 저그");
INSERT items (id, name_en, name_kr) VALUES(7108, "hermit crab model", "소라게 모형");
INSERT items (id, name_en, name_kr) VALUES(891, "holiday candle", "크리스마스 양초");
INSERT items (id, name_en, name_kr) VALUES(3968, "homework set", "공부 세트");
INSERT items (id, name_en, name_kr) VALUES(5928, "honeybee model", "꿀벌 모형");
INSERT items (id, name_en, name_kr) VALUES(7075, "horned atlas model", "코카서스장수풍뎅이 모형");
INSERT items (id, name_en, name_kr) VALUES(5938, "horned dynastid model", "장수풍뎅이 모형");
INSERT items (id, name_en, name_kr) VALUES(7110, "horned elephant model", "코끼리장수풍뎅이 모형");
INSERT items (id, name_en, name_kr) VALUES(6932, "horse mackerel model", "전갱이 모형");
INSERT items (id, name_en, name_kr) VALUES(1892, "hourglass", "모래시계");
INSERT items (id, name_en, name_kr) VALUES(690, "hula doll", "훌라 댄스 인형");
INSERT items (id, name_en, name_kr) VALUES(1836, "humidifier", "가습기");
INSERT items (id, name_en, name_kr) VALUES(7234, "hyacinth lamp", "히아신스 전등");
INSERT items (id, name_en, name_kr) VALUES(997, "incense burner", "향");
INSERT items (id, name_en, name_kr) VALUES(4107, "infused-water dispenser", "프루츠 워터 디스펜서");
INSERT items (id, name_en, name_kr) VALUES(1838, "ironing set", "다리미");
INSERT items (id, name_en, name_kr) VALUES(7099, "jewel beetle model", "비단벌레 모형");
INSERT items (id, name_en, name_kr) VALUES(1456, "judge's bell", "시합을 알리는 공");
INSERT items (id, name_en, name_kr) VALUES(3407, "katana", "일본도");
INSERT items (id, name_en, name_kr) VALUES(724, "kettle", "주전자");
INSERT items (id, name_en, name_kr) VALUES(7535, "kettlebell", "케틀벨");
INSERT items (id, name_en, name_kr) VALUES(6985, "killifish model", "송사리 모형");
INSERT items (id, name_en, name_kr) VALUES(6978, "king salmon model", "왕연어 모형");
INSERT items (id, name_en, name_kr) VALUES(7804, "knife block", "칼꽂이");
INSERT items (id, name_en, name_kr) VALUES(6991, "koi model", "비단잉어 모형");
INSERT items (id, name_en, name_kr) VALUES(4016, "lab-experiments set", "실험 세트");
INSERT items (id, name_en, name_kr) VALUES(7102, "ladybug model", "무당벌레 모형");
INSERT items (id, name_en, name_kr) VALUES(1432, "lantern", "랜턴");
INSERT items (id, name_en, name_kr) VALUES(1850, "laptop", "노트북");
INSERT items (id, name_en, name_kr) VALUES(3333, "LCD TV (20 in.)", "20인치 탁상용 TV");
INSERT items (id, name_en, name_kr) VALUES(3252, "LCD TV (50 in.)", "50인치 탁상용 TV");
INSERT items (id, name_en, name_kr) VALUES(3774, "Libra scale", "천칭자리 저울");
INSERT items (id, name_en, name_kr) VALUES(7148, "life ring", "튜브");
INSERT items (id, name_en, name_kr) VALUES(6944, "loach model", "미꾸라지 모형");
INSERT items (id, name_en, name_kr) VALUES(7097, "long locust model", "방아깨비 모형");
INSERT items (id, name_en, name_kr) VALUES(131, "lucky cat", "복고양이");
INSERT items (id, name_en, name_kr) VALUES(9814, "lucky gold cat", "금색 복고양이");
INSERT items (id, name_en, name_kr) VALUES(7117, "M. sunset moth model", "마다가스카르비단제비나방 모형");
INSERT items (id, name_en, name_kr) VALUES(3586, "magazine", "잡지");
INSERT items (id, name_en, name_kr) VALUES(1032, "magazine rack", "잡지 꽂이");
INSERT items (id, name_en, name_kr) VALUES(4392, "magic kit", "마술 세트");
INSERT items (id, name_en, name_kr) VALUES(7014, "mahi-mahi model", "만새기 모형");
INSERT items (id, name_en, name_kr) VALUES(7116, "man-faced stink bug model", "인면노린재 모형");
INSERT items (id, name_en, name_kr) VALUES(7068, "mantis model", "사마귀 모형");
INSERT items (id, name_en, name_kr) VALUES(1652, "matryoshka", "마트료시카");
INSERT items (id, name_en, name_kr) VALUES(7262, "metal can", "사각 깡통");
INSERT items (id, name_en, name_kr) VALUES(1042, "metronome", "메트로놈");
INSERT items (id, name_en, name_kr) VALUES(1319, "microscope", "현미경");
INSERT items (id, name_en, name_kr) VALUES(1043, "microwave", "전자레인지");
INSERT items (id, name_en, name_kr) VALUES(7103, "migratory locust model", "섬풀무치 모형");
INSERT items (id, name_en, name_kr) VALUES(4123, "mini-cactus set", "미니 선인장 세트");
INSERT items (id, name_en, name_kr) VALUES(7019, "mitten crab model", "참게 모형");
INSERT items (id, name_en, name_kr) VALUES(1050, "mixer", "믹서");
INSERT items (id, name_en, name_kr) VALUES(7083, "miyama stag model", "사슴벌레 모형");
INSERT items (id, name_en, name_kr) VALUES(7258, "modeling clay", "점토 장난감");
INSERT items (id, name_en, name_kr) VALUES(7089, "mole cricket model", "땅강아지 모형");
INSERT items (id, name_en, name_kr) VALUES(7143, "Mom's candle set", "엄마의 양초");
INSERT items (id, name_en, name_kr) VALUES(7144, "Mom's cushion", "엄마의 쿠션");
INSERT items (id, name_en, name_kr) VALUES(7146, "Mom's homemade cake", "엄마의 수제 케이크");
INSERT items (id, name_en, name_kr) VALUES(7141, "Mom's pen stand", "엄마의 연필꽂이");
INSERT items (id, name_en, name_kr) VALUES(7147, "Mom's plushie", "엄마의 솜인형");
INSERT items (id, name_en, name_kr) VALUES(7138, "Mom's tea cozy", "엄마의 주전자 커버");
INSERT items (id, name_en, name_kr) VALUES(7140, "Mom's tissue box", "엄마의 티슈 케이스");
INSERT items (id, name_en, name_kr) VALUES(7091, "monarch butterfly model", "왕나비 모형");
INSERT items (id, name_en, name_kr) VALUES(7025, "moray eel model", "곰치 모형");
INSERT items (id, name_en, name_kr) VALUES(5936, "mosquito model", "모기 모형");
INSERT items (id, name_en, name_kr) VALUES(109, "moss ball", "이끼 볼");
INSERT items (id, name_en, name_kr) VALUES(7056, "moth model", "나방 모형");
INSERT items (id, name_en, name_kr) VALUES(1870, "mug", "머그컵");
INSERT items (id, name_en, name_kr) VALUES(4076, "nail-art set", "네일아트 세트");
INSERT items (id, name_en, name_kr) VALUES(6989, "Napoleonfish model", "나폴레옹피시 모형");
INSERT items (id, name_en, name_kr) VALUES(6990, "neon tetra model", "네온테트라 모형");
INSERT items (id, name_en, name_kr) VALUES(8464, "Newton's cradle", "뉴턴의 요람");
INSERT items (id, name_en, name_kr) VALUES(6945, "nibble fish model", "닥터피시 모형");
INSERT items (id, name_en, name_kr) VALUES(12543, "Nintendo Switch", "Nintendo Switch");
INSERT items (id, name_en, name_kr) VALUES(6826, "nova light", "별 조명");
INSERT items (id, name_en, name_kr) VALUES(7284, "nutcracker", "호두까기 인형");
INSERT items (id, name_en, name_kr) VALUES(7011, "oarfish model", "산갈치 모형");
INSERT items (id, name_en, name_kr) VALUES(3654, "oil lamp", "알코올램프");
INSERT items (id, name_en, name_kr) VALUES(4111, "old-fashioned alarm clock", "종소리 알람 시계");
INSERT items (id, name_en, name_kr) VALUES(4393, "old-fashioned washtub", "빨랫대야");
INSERT items (id, name_en, name_kr) VALUES(6957, "olive flounder model", "넙치 모형");
INSERT items (id, name_en, name_kr) VALUES(7061, "orchid mantis model", "연꽃사마귀 모형");
INSERT items (id, name_en, name_kr) VALUES(3965, "painting set", "그림 그리기 세트");
INSERT items (id, name_en, name_kr) VALUES(7000, "pale chub model", "피라미 모형");
INSERT items (id, name_en, name_kr) VALUES(7112, "paper kite butterfly model", "왕얼룩나비 모형");
INSERT items (id, name_en, name_kr) VALUES(689, "paper tiger", "종이호랑이");
INSERT items (id, name_en, name_kr) VALUES(4128, "peach surprise box", "복숭아 깜짝 상자");
INSERT items (id, name_en, name_kr) VALUES(7071, "peacock butterfly model", "제비나비 모형");
INSERT items (id, name_en, name_kr) VALUES(7257, "pedal board", "이펙터 세트");
INSERT items (id, name_en, name_kr) VALUES(7801, "pet food bowl", "반려동물 사료 그릇");
INSERT items (id, name_en, name_kr) VALUES(794, "phonograph", "축음기");
INSERT items (id, name_en, name_kr) VALUES(1082, "picnic basket", "피크닉 가방");
INSERT items (id, name_en, name_kr) VALUES(7004, "pike model", "강꼬치고기 모형");
INSERT items (id, name_en, name_kr) VALUES(7054, "pill bug model", "공벌레 모형");
INSERT items (id, name_en, name_kr) VALUES(3802, "pine bonsai tree", "소나무 분재");
INSERT items (id, name_en, name_kr) VALUES(7005, "piranha model", "피라니아 모형");
INSERT items (id, name_en, name_kr) VALUES(4105, "plasma ball", "플라즈마 볼");
INSERT items (id, name_en, name_kr) VALUES(1881, "plastic canister", "플라스틱 액체 용기");
INSERT items (id, name_en, name_kr) VALUES(12372, "Pocket modern camper", "캠핑카 모형 B");
INSERT items (id, name_en, name_kr) VALUES(12373, "Pocket vintage camper", "캠핑카 모형 A");
INSERT items (id, name_en, name_kr) VALUES(7026, "pond smelt model", "빙어 모형");
INSERT items (id, name_en, name_kr) VALUES(7052, "pondskater model", "소금쟁이 모형");
INSERT items (id, name_en, name_kr) VALUES(6942, "pop-eyed goldfish model", "툭눈금붕어 모형");
INSERT items (id, name_en, name_kr) VALUES(3282, "pop-up toaster", "토스터기");
INSERT items (id, name_en, name_kr) VALUES(3697, "portable radio", "휴대용 라디오");
INSERT items (id, name_en, name_kr) VALUES(4338, "portable record player", "휴대용 레코드플레이어");
INSERT items (id, name_en, name_kr) VALUES(2559, "pot", "항아리");
INSERT items (id, name_en, name_kr) VALUES(3822, "pro tape recorder", "오픈릴 녹음기");
INSERT items (id, name_en, name_kr) VALUES(7800, "protein shaker bottle", "단백질 보충제");
INSERT items (id, name_en, name_kr) VALUES(6956, "puffer fish model", "가시복 모형");
INSERT items (id, name_en, name_kr) VALUES(7049, "R. Brooke's birdwing model", "붉은목도리비단나비 모형");
INSERT items (id, name_en, name_kr) VALUES(7088, "rainbow stag model", "뮤엘러리사슴벌레 모형");
INSERT items (id, name_en, name_kr) VALUES(7008, "rainbowfish model", "레인보우피시 모형");
INSERT items (id, name_en, name_kr) VALUES(7009, "ranchu goldfish model", "난주 모형");
INSERT items (id, name_en, name_kr) VALUES(4050, "rattan table lamp", "라탄 테이블 램프");
INSERT items (id, name_en, name_kr) VALUES(4048, "rattan towel basket", "라탄 수건 바구니");
INSERT items (id, name_en, name_kr) VALUES(6949, "ray model", "가오리 모형");
INSERT items (id, name_en, name_kr) VALUES(8096, "record box", "레코드 박스");
INSERT items (id, name_en, name_kr) VALUES(7045, "recycled-can thumb piano", "깡통 칼림바");
INSERT items (id, name_en, name_kr) VALUES(7050, "red dragonfly model", "고추잠자리 모형");
INSERT items (id, name_en, name_kr) VALUES(7020, "red snapper model", "도미 모형");
INSERT items (id, name_en, name_kr) VALUES(12565, "Reese & Cyrus photo plate", "리사와 리포 그림 그릇");
INSERT items (id, name_en, name_kr) VALUES(1125, "revolving spice rack", "조미료 바구니");
INSERT items (id, name_en, name_kr) VALUES(6955, "ribbon eel model", "리본장어 모형");
INSERT items (id, name_en, name_kr) VALUES(1888, "rice cooker", "전기밥솥");
INSERT items (id, name_en, name_kr) VALUES(7067, "rice grasshopper model", "메뚜기 모형");
INSERT items (id, name_en, name_kr) VALUES(1889, "ring", "반지");
INSERT items (id, name_en, name_kr) VALUES(88, "ringtoss", "고리 던지기");
INSERT items (id, name_en, name_kr) VALUES(7081, "robust cicada model", "참매미 모형");
INSERT items (id, name_en, name_kr) VALUES(7119, "rosalia batesi beetle model", "루리하늘소 모형");
INSERT items (id, name_en, name_kr) VALUES(4029, "rotary phone", "다이얼 전화기");
INSERT items (id, name_en, name_kr) VALUES(12472, "Rover's briefcase", "낯선고양이 가방");
INSERT items (id, name_en, name_kr) VALUES(6950, "saddled bichir model", "엔드리케리 모형");
INSERT items (id, name_en, name_kr) VALUES(7012, "salmon model", "연어 모형");
INSERT items (id, name_en, name_kr) VALUES(7002, "saw shark model", "톱상어 모형");
INSERT items (id, name_en, name_kr) VALUES(5922, "saw stag model", "톱사슴벌레 모형");
INSERT items (id, name_en, name_kr) VALUES(5929, "scarab beetle model", "보석풍뎅이 모형");
INSERT items (id, name_en, name_kr) VALUES(5962, "Scorpio lamp", "전갈자리 램프");
INSERT items (id, name_en, name_kr) VALUES(7094, "scorpion model", "전갈 모형");
INSERT items (id, name_en, name_kr) VALUES(7018, "sea bass model", "농어 모형");
INSERT items (id, name_en, name_kr) VALUES(6982, "sea butterfly model", "클리오네 모형");
INSERT items (id, name_en, name_kr) VALUES(1124, "sea globe", "해저볼");
INSERT items (id, name_en, name_kr) VALUES(7021, "sea horse model", "해마 모형");
INSERT items (id, name_en, name_kr) VALUES(1128, "sewing machine", "재봉틀");
INSERT items (id, name_en, name_kr) VALUES(3443, "sewing project", "바느질 세트");
INSERT items (id, name_en, name_kr) VALUES(667, "shaved-ice maker", "팥빙수 기계");
INSERT items (id, name_en, name_kr) VALUES(3984, "shell lamp", "조개 램프");
INSERT items (id, name_en, name_kr) VALUES(5150, "shell speaker", "조개 스피커");
INSERT items (id, name_en, name_kr) VALUES(1204, "silver bug trophy", "은 곤충 트로피");
INSERT items (id, name_en, name_kr) VALUES(1201, "silver fish trophy", "은 물고기 트로피");
INSERT items (id, name_en, name_kr) VALUES(7100, "silver HHA trophy", "집 모양 은 트로피");
INSERT items (id, name_en, name_kr) VALUES(1845, "simple kettle", "심플 주전자");
INSERT items (id, name_en, name_kr) VALUES(7072, "snail model", "달팽이 모형");
INSERT items (id, name_en, name_kr) VALUES(6964, "snapping turtle model", "늑대거북 모형");
INSERT items (id, name_en, name_kr) VALUES(1145, "snow globe", "스노글로브");
INSERT items (id, name_en, name_kr) VALUES(7017, "soft-shelled turtle model", "자라 모형");
INSERT items (id, name_en, name_kr) VALUES(3619, "soup kettle", "수프 워머");
INSERT items (id, name_en, name_kr) VALUES(7079, "spider model", "거미 모형");
INSERT items (id, name_en, name_kr) VALUES(6958, "squid model", "오징어 모형");
INSERT items (id, name_en, name_kr) VALUES(1759, "stack of books", "쌓인 책");
INSERT items (id, name_en, name_kr) VALUES(1861, "stacked magazines", "쌓인 잡지");
INSERT items (id, name_en, name_kr) VALUES(4019, "stand mixer", "스탠드 믹서");
INSERT items (id, name_en, name_kr) VALUES(7253, "star clock", "별 시계");
INSERT items (id, name_en, name_kr) VALUES(3344, "steamer-basket set", "나무 찜통");
INSERT items (id, name_en, name_kr) VALUES(7069, "stinkbug model", "노린재 모형");
INSERT items (id, name_en, name_kr) VALUES(8297, "stovetop espresso maker", "에스프레소 메이커");
INSERT items (id, name_en, name_kr) VALUES(6960, "stringfish model", "일본연어 모형");
INSERT items (id, name_en, name_kr) VALUES(3442, "sturdy sewing box", "수예 상자");
INSERT items (id, name_en, name_kr) VALUES(7023, "sturgeon model", "철갑상어 모형");
INSERT items (id, name_en, name_kr) VALUES(132, "succulent plant", "다육 식물");
INSERT items (id, name_en, name_kr) VALUES(6979, "suckerfish model", "빨판상어 모형");
INSERT items (id, name_en, name_kr) VALUES(6988, "surgeonfish model", "블루탱 모형");
INSERT items (id, name_en, name_kr) VALUES(6936, "sweetfish model", "은어 모형");
INSERT items (id, name_en, name_kr) VALUES(4069, "table lamp", "테이블 램프");
INSERT items (id, name_en, name_kr) VALUES(4068, "table setting", "테이블 세팅");
INSERT items (id, name_en, name_kr) VALUES(4067, "tabletop festive tree", "탁상 크리스마스트리");
INSERT items (id, name_en, name_kr) VALUES(7001, "tadpole model", "올챙이 모형");
INSERT items (id, name_en, name_kr) VALUES(787, "tape deck", "카세트라디오");
INSERT items (id, name_en, name_kr) VALUES(7101, "tarantula model", "타란툴라 모형");
INSERT items (id, name_en, name_kr) VALUES(3467, "tea set", "티 세트");
INSERT items (id, name_en, name_kr) VALUES(3773, "terrarium", "테라리움");
INSERT items (id, name_en, name_kr) VALUES(12471, "thank-you Dad mug", "아버지날 감사 머그컵");
INSERT items (id, name_en, name_kr) VALUES(12470, "thank-you Mom mug", "어머니날 감사 머그컵");
INSERT items (id, name_en, name_kr) VALUES(4762, "throwback container", "TOY 철제 박스");
INSERT items (id, name_en, name_kr) VALUES(4754, "throwback gothic mirror", "TOY 거울");
INSERT items (id, name_en, name_kr) VALUES(4757, "throwback skull radio", "TOY 오디오");
INSERT items (id, name_en, name_kr) VALUES(4753, "throwback wrestling figure", "TOY 피규어");
INSERT items (id, name_en, name_kr) VALUES(7062, "tiger beetle model", "길앞잡이 모형");
INSERT items (id, name_en, name_kr) VALUES(5944, "tiger butterfly model", "호랑나비 모형");
INSERT items (id, name_en, name_kr) VALUES(7022, "tilapia model", "틸라피아 모형");
INSERT items (id, name_en, name_kr) VALUES(2592, "tin bucket", "양철 양동이");
INSERT items (id, name_en, name_kr) VALUES(4114, "tissue box", "갑 티슈");
INSERT items (id, name_en, name_kr) VALUES(4687, "toolbox", "공구 상자");
INSERT items (id, name_en, name_kr) VALUES(3623, "toy box", "장난감 상자");
INSERT items (id, name_en, name_kr) VALUES(3969, "toy centipede", "장난감 지네");
INSERT items (id, name_en, name_kr) VALUES(3620, "toy cockroach", "장난감 바퀴벌레");
INSERT items (id, name_en, name_kr) VALUES(5975, "traditional balancing toy", "균형 잡기 장난감");
INSERT items (id, name_en, name_kr) VALUES(4033, "traditional tea set", "전통 티 세트");
INSERT items (id, name_en, name_kr) VALUES(1823, "trash bags", "쓰레기봉투");
INSERT items (id, name_en, name_kr) VALUES(6078, "tree's bounty lamp", "나무 열매 램프");
INSERT items (id, name_en, name_kr) VALUES(6079, "tree's bounty little tree", "작은 나무 열매 트리");
INSERT items (id, name_en, name_kr) VALUES(6983, "tuna model", "다랑어 모형");
INSERT items (id, name_en, name_kr) VALUES(1211, "typewriter", "타자기");
INSERT items (id, name_en, name_kr) VALUES(669, "ukulele", "우쿨렐레");
INSERT items (id, name_en, name_kr) VALUES(4308, "unfinished puzzle", "미완성 퍼즐");
INSERT items (id, name_en, name_kr) VALUES(4025, "unglazed dish set", "질그릇 세트");
INSERT items (id, name_en, name_kr) VALUES(7105, "violin beetle model", "바이올린벌레 모형");
INSERT items (id, name_en, name_kr) VALUES(7104, "walker cicada model", "애매미 모형");
INSERT items (id, name_en, name_kr) VALUES(7076, "walking leaf model", "잎사귀벌레 모형");
INSERT items (id, name_en, name_kr) VALUES(7087, "walking stick model", "긴수염대벌레 모형");
INSERT items (id, name_en, name_kr) VALUES(5927, "wasp model", "벌 모형");
INSERT items (id, name_en, name_kr) VALUES(12403, "wedding cake", "웨딩 케이크");
INSERT items (id, name_en, name_kr) VALUES(12408, "wedding candle set", "웨딩 양초");
INSERT items (id, name_en, name_kr) VALUES(6961, "whale shark model", "고래상어 모형");
INSERT items (id, name_en, name_kr) VALUES(7055, "wharf roach model", "갯강구 모형");
INSERT items (id, name_en, name_kr) VALUES(7233, "windflower fan", "아네모네 선풍기");
INSERT items (id, name_en, name_kr) VALUES(12412, "Wobbling Zipper toy", "토빗 오뚝이");
INSERT items (id, name_en, name_kr) VALUES(4124, "wooden fish", "목탁");
INSERT items (id, name_en, name_kr) VALUES(8826, "wooden table mirror", "목제 테이블 거울");
INSERT items (id, name_en, name_kr) VALUES(7454, "wooden toolbox", "목제 공구 상자");
INSERT items (id, name_en, name_kr) VALUES(3206, "wooden-block toy", "나무블록 장난감");
INSERT items (id, name_en, name_kr) VALUES(7084, "yellow butterfly model", "노랑나비 모형");
INSERT items (id, name_en, name_kr) VALUES(7028, "yellow perch model", "옐로우퍼치 모형");
INSERT items (id, name_en, name_kr) VALUES(7836, "zebra turkeyfish model", "쏨뱅이 모형");






INSERT tagas (category, content) VALUES('type', '잡화');
SET @miscellaneous_tag_id = (SELECT id FROM tags WHERE content LIKE '잡화');

INSERT  item_tags (tag_id, item_id) 
SELECT  @miscellaneous_tag_id, items.id 
FROM    items
WHERE   ;

